variable project {}
variable lambda_function_arn {}
variable training_instance_type {}
variable volume_size_sagemaker {}
variable ecr_repository_url {}
variable bucket_output_models {}
variable sagemaker_exec_role_arn {}
variable bucket_training_data {}
variable inference_instance_type {}
variable sf_exec_role_arn {}
